# toolchain-riscv.cmake
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

# Set toolchain path
set(RISCV_TOOLCHAIN_PATH /workspace/toolchains/riscv-toolchain)
set(RISCV_TOOLCHAIN_PREFIX riscv64-unknown-elf-)

# Set compilers
set(CMAKE_C_COMPILER ${RISCV_TOOLCHAIN_PATH}/bin/${RISCV_TOOLCHAIN_PREFIX}gcc)
set(CMAKE_C_STANDARD 23)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_COMPILER ${RISCV_TOOLCHAIN_PATH}/bin/${RISCV_TOOLCHAIN_PREFIX}g++)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_ASM_COMPILER ${RISCV_TOOLCHAIN_PATH}/bin/${RISCV_TOOLCHAIN_PREFIX}gcc)
set(CMAKE_AR ${RISCV_TOOLCHAIN_PATH}/bin/${RISCV_TOOLCHAIN_PREFIX}ar)
set(CMAKE_OBJCOPY ${RISCV_TOOLCHAIN_PATH}/bin/${RISCV_TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_OBJDUMP ${RISCV_TOOLCHAIN_PATH}/bin/${RISCV_TOOLCHAIN_PREFIX}objdump)

# Set Arch and ABI
set(CMAKE_C_FLAGS "-march=rv64gcv_zfh_zvfh -mabi=lp64d" CACHE STRING "C flags")
set(CMAKE_CXX_FLAGS "-march=rv64gcv_zfh_zvfh -mabi=lp64d" CACHE STRING "C++ flags")
set(CMAKE_ASM_FLAGS "-march=rv64gcv_zfh_zvfh -mabi=lp64d" CACHE STRING "ASM flags")
set(CMAKE_EXE_LINKER_FLAGS "-march=rv64gcv_zfh_zvfh -mabi=lp64d" CACHE STRING "Linker flags")

# Disabling CMake's default tests
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

# Set find root
set(CMAKE_FIND_ROOT_PATH ${RISCV_TOOLCHAIN_PATH}/${RISCV_TOOLCHAIN_PREFIX})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
