services:
  daily_dev:
    image: daily_dev:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily_dev
    network_mode: bridge
    user: "1000:0"
    restart: always
    tty: true
    privileged: true
    ports:
      - "15822:22"
      - "15888:8888"
    volumes:
      - /home/george/workspace/daily-dev:/workspace
      - /home/george/.vscode-server/:/home/george/.vscode-server/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
    command: ["sleep", "infinity"]
