services:
  daily_dev:
    image: daily_dev:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily_dev
    network_mode: bridge
    user: "1000:0"
    restart: always
    tty: true
    privileged: true
    ports:
      - "14222:22"
      - "14288:8888"
    volumes:
      - /home/george/workspace/daily_dev:/workspace
      - /home/george/.vscode-server/:/home/george/.vscode-server/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
